added a scaling factor for the weather icons
aceisace/Inkycal pull request #194
Opened 2021-06-03 23:05 UTC by emilyboda

As ace and I discussed a while back (mid-2020?) the unicode weather icons report an incorrect size in the y direction. Some of the icon's sizes are off by enough that the human eye can see that they are no longer centered in the y direction. 

During another project of mine, I went through each icon and added a manual scaling factor that, when used along with the font size, can help us properly center the icons. I had difficulty integrating that scaling factor into the weather module because it's a very complicated program and ace wrote it. 

But I think I figured it out: By editing the y alignment line in the draw_icon function to factor in this size correction, all the icons are now correctly centered. That appears to be the case with my 12" screen, although I haven't yet tested it on a 7.5" screen. I would appreciate others testing this out for me and seeing if there's any ill-effects on smaller screens.

2022-08-27 11:19 UTC, aceisace commented
@emilyboda Hi, been a while! Thanks for your PR!
Apologies for getting back late. Could you please target the `feature/venv`branch for this? Then I can have it merged once I have tested it 👍

2023-02-10 13:53 UTC, ch3lmi requested changes
Please do not merge this, it is missing some essential mappings in the icon_size_correction table.
I have a modified version available that includes the missing ones.

2023-02-13 08:24 UTC, ch3lmi requested changes
I have tested this on a 12.48" WaveShare Colour display and it looks good, except that you missed some of the mapping for the moon phase which causes inkycal to crash when in this phase.
Please use this mapping table instead: 

      icon_size_correction =   {
        '\uf00d': 10/60,  '\uf02e': 51/150, '\uf019': 21/60,
        '\uf01b': 21/60,  '\uf0b5': 51/150, '\uf050': 25/60,
        '\uf013': 51/150, '\uf002': 0,      '\uf031': 29/100,
        '\uf015': 21/60,  '\uf01e': 52/150, '\uf056': 51/150,
        '\uf053': 14/150, '\uf012': 51/150, '\uf01a': 51/150,
        '\uf014': 51/150, '\uf037': 42/150, '\uf036': 42/150, 
        '\uf03b': 42/150, '\uf038': 42/150, '\uf023': 35/150,
        '\uf07a': 35/150, '\uf051': 18/150, '\uf052': 18/150,
        '\uf0aa': 0, '\uf095': 0, '\uf099': 0, '\uf09c': 0,
        '\uf0a0': 0, '\uf0a3': 0, '\uf0a7': 0, '\uf0aa': 0,
        '\uf0ae': 0
        }

2023-02-14 08:09 UTC, ch3lmi requested changes
Please use this table instead

2023-02-14 08:09 UTC, ch3lmi commented on inkycal/modules/inkycal_weather.py
> +        }
icon_size_correction =   {
    '\uf00d': 10/60,  '\uf02e': 51/150, '\uf019': 21/60,
    '\uf01b': 21/60,  '\uf0b5': 51/150, '\uf050': 25/60,
    '\uf013': 51/150, '\uf002': 0,      '\uf031': 29/100,
    '\uf015': 21/60,  '\uf01e': 52/150, '\uf056': 51/150,
    '\uf053': 14/150, '\uf012': 51/150, '\uf01a': 51/150,
    '\uf014': 51/150, '\uf037': 42/150, '\uf036': 42/150, 
    '\uf03b': 42/150, '\uf038': 42/150, '\uf023': 35/150,
    '\uf07a': 35/150, '\uf051': 18/150, '\uf052': 18/150,
    '\uf0aa': 0, '\uf095': 0, '\uf099': 0, '\uf09c': 0,
    '\uf0a0': 0, '\uf0a3': 0, '\uf0a7': 0, '\uf0aa': 0,
    '\uf0ae': 0
    }

2023-02-14 20:55 UTC, aceisace commented
Please check the merge conflict so this can be merged

2023-02-14 21:57 UTC, aceisace commented
Unittest passed!
Thanks for your help and effort @emilyboda and @ch3lmi 
Attached is the code using the latest version of inkycal_weather combined with the lastest changes from this PR:
```py
#!python3

"""
Inkycal weather module
Copyright by aceisace
"""

from inkycal.modules.template import inkycal_module
from inkycal.custom import *

import math
import decimal
import arrow

from pyowm.owm import OWM

logger = logging.getLogger(__name__)


class Weather(inkycal_module):
    """Weather class
    parses weather details from openweathermap
    """
    name = "Weather (openweathermap) - Get weather forecasts from openweathermap"

    requires = {

        "api_key": {
            "label": "Please enter openweathermap api-key. You can create one for free on openweathermap",
        },

        "location": {
            "label": "Please enter your location in the following format: City, Country-Code. " +
                     "You can also enter the location ID found in the url " +
                     "e.g. https://openweathermap.org/city/4893171 -> ID is 4893171"
        }
    }

    optional = {

        "round_temperature": {
            "label": "Round temperature to the nearest degree?",
            "options": [True, False],
        },

        "round_windspeed": {
            "label": "Round windspeed?",
            "options": [True, False],
        },

        "forecast_interval": {
            "label": "Please select the forecast interval",
            "options": ["daily", "hourly"],
        },

        "units": {
            "label": "Which units should be used?",
            "options": ["metric", "imperial"],
        },

        "hour_format": {
            "label": "Which hour format do you prefer?",
            "options": [24, 12],
        },

        "use_beaufort": {
            "label": "Use beaufort scale for windspeed?",
            "options": [True, False],
        },

    }

    def __init__(self, config):
        """Initialize inkycal_weather module"""

        super().__init__(config)

        config = config['config']

        # Check if all required parameters are present
        for param in self.requires:
            if not param in config:
                raise Exception(f'config is missing {param}')

        # required parameters
        self.api_key = config['api_key']
        self.location = config['location']

        # optional parameters
        self.round_temperature = config['round_temperature']
        self.round_windspeed = config['round_windspeed']
        self.forecast_interval = config['forecast_interval']
        self.units = config['units']
        self.hour_format = int(config['hour_format'])
        self.use_beaufort = config['use_beaufort']

        # additional configuration
        self.owm = OWM(self.api_key).weather_manager()
        self.timezone = get_system_tz()
        self.locale = config['language']
        self.weatherfont = ImageFont.truetype(
            fonts['weathericons-regular-webfont'], size=self.fontsize)

        # give an OK message
        print(f"{__name__} loaded")

    def generate_image(self):
        """Generate image for this module"""

        # Define new image size with respect to padding
        im_width = int(self.width - (2 * self.padding_left))
        im_height = int(self.height - (2 * self.padding_top))
        im_size = im_width, im_height
        logger.info(f'Image size: {im_size}')

        # Create an image for black pixels and one for coloured pixels
        im_black = Image.new('RGB', size=im_size, color='white')
        im_colour = Image.new('RGB', size=im_size, color='white')

        # Check if internet is available
        if internet_available():
            logger.info('Connection test passed')
        else:
            raise NetworkNotReachableError

        def get_moon_phase():
            """Calculate the current (approximate) moon phase"""

            dec = decimal.Decimal
            diff = now - arrow.get(2001, 1, 1)
            days = dec(diff.days) + (dec(diff.seconds) / dec(86400))
            lunations = dec("0.20439731") + (days * dec("0.03386319269"))
            position = lunations % dec(1)
            index = math.floor((position * dec(8)) + dec("0.5"))
            return {
                0: '\uf095',
                1: '\uf099',
                2: '\uf09c',
                3: '\uf0a0',
                4: '\uf0a3',
                5: '\uf0a7',
                6: '\uf0aa',
                7: '\uf0ae'}[int(index) & 7]

        def is_negative(temp):
            """Check if temp is below freezing point of water (0°C/30°F)
            returns True if temp below freezing point, else False"""
            answer = False

            if temp_unit == 'celsius' and round(float(temp.split('°')[0])) <= 0:
                answer = True
            elif temp_unit == 'fahrenheit' and round(float(temp.split('°')[0])) <= 0:
                answer = True
            return answer

        # Lookup-table for weather icons and weather codes
        weathericons = {
            '01d': '\uf00d',
            '02d': '\uf002',
            '03d': '\uf013',
            '04d': '\uf012',
            '09d': '\uf01a',
            '10d': '\uf019',
            '11d': '\uf01e',
            '13d': '\uf01b',
            '50d': '\uf014',
            '01n': '\uf02e',
            '02n': '\uf013',
            '03n': '\uf013',
            '04n': '\uf013',
            '09n': '\uf037',
            '10n': '\uf036',
            '11n': '\uf03b',
            '13n': '\uf038',
            '50n': '\uf023'
        }

        def draw_icon(image, xy, box_size, icon, rotation=None):
            """Custom function to add icons of weather font on image
            image = on which image should the text be added?
            xy = xy-coordinates as tuple -> (x,y)
            box_size = size of text-box -> (width,height)
            icon = icon-unicode, looks this up in weathericons dictionary
            """

            icon_size_correction = {
                '\uf00d': 10 / 60,
                '\uf02e': 51 / 150,
                '\uf019': 21 / 60,
                '\uf01b': 21 / 60,
                '\uf0b5': 51 / 150,
                '\uf050': 25 / 60,
                '\uf013': 51 / 150,
                '\uf002': 0,
                '\uf031': 29 / 100,
                '\uf015': 21 / 60,
                '\uf01e': 52 / 150,
                '\uf056': 51 / 150,
                '\uf053': 14 / 150,
                '\uf012': 51 / 150,
                '\uf01a': 51 / 150,
                '\uf014': 51 / 150,
                '\uf037': 42 / 150,
                '\uf036': 42 / 150,
                '\uf03b': 42 / 150,
                '\uf038': 42 / 150,
                '\uf023': 35 / 150,
                '\uf07a': 35 / 150,
                '\uf051': 18 / 150,
                '\uf052': 18 / 150,
                '\uf0aa': 0,
                '\uf095': 0,
                '\uf099': 0,
                '\uf09c': 0,
                '\uf0a0': 0,
                '\uf0a3': 0,
                '\uf0a7': 0,
                '\uf0aa': 0,
                '\uf0ae': 0
            }

            x, y = xy
            box_width, box_height = box_size
            text = icon
            font = self.weatherfont

            # Increase fontsize to fit specified height and width of text box
            size = 8
            font = ImageFont.truetype(font.path, size)
            text_width, text_height = font.getsize(text)

            while (text_width < int(box_width * 0.9) and
                   text_height < int(box_height * 0.9)):
                size += 1
                font = ImageFont.truetype(font.path, size)
                text_width, text_height = font.getsize(text)

            text_width, text_height = font.getsize(text)

            # Align text to desired position
            x = int((box_width / 2) - (text_width / 2))
            y = int((box_height / 2) - (text_height / 2) - (icon_size_correction[icon] * size) / 2)

   [...]

2023-02-14 21:57 UTC, merged